variables:
  IMAGE: "artifactory.gns.cri.nz/gns/pumahu:0.1"
  APP_NAME: "Pumahu"
  APP_SERVER: "Vulkan"
  TEAM: "Volcano"

stages:
  - test
  - build
  - deploy

test:
  image: python:3.8
  tags:
    - docker
  stage: test
  variables:
    TRAVIS: "true"
  before_script:
  - apt-get -y update && apt-get -y install cmake
  - python -V  # Print out python version for debugging
  script:
    - python -c "import os; print(os.environ)"
    - pip install numpy
    - pip install -r requirements.txt
    - python setup.py develop
    - pip install pytest flake8  # you can also use tox
    - pytest tests/
  allow_failure: true

build:
  tags:
    - linux
  stage: build
  script:
    - bash docker_build.sh -i "$IMAGE"

deploy-processing:
  tags:
    - linux
  stage: deploy
  script: |
    DOCKER_CMD=(Cmd:='["python", "./pumahu/job_scheduler.py"]')
    bash docker_deploy.sh -i "$IMAGE" -a "$APP_NAME" -s "$APP_SERVER" -t "$TEAM" -c "${DOCKER_CMD[@]}"
    

deploy-api:
  tags:
    - linux
  stage: deploy
  script:
    DOCKER_CMD=(Cmd:='["heat_api"]')
    - bash docker_deploy.sh -i "$IMAGE" -a "$APP_NAME" -s "$APP_SERVER" -t "$TEAM" -c "${DOCKER_CMD[@]}"


