variables:
  IMAGE: "pumahu"
  TAG: "0.0.1"
stages:
  - build

build:
  tags:
    - linux
  stage: build
  script:
    - ./buildnrun.sh -b --image $IMAGE --tag $TAG
    - ./buildnrun.sh --registry "huta17-d:5000" --image $IMAGE --tag $TAG
