variables:
  - IMAGE: "huta17-d:5000/yannik/pumahu"
  - TAG: "0.0.1"
stages:
  - build

build:
  tags:
    - linux
  stage: build
  script:
    - ./buildnrun.sh -b --image $IMAGE --tag $TAG
    - docker image push "$IMAGE:$TAG"
