stages:
  - build
  - deploy

build:
  tags:
    - linux
  stage: build
  script:
    - ./buildnrun.sh -b 
    - ./buildnrun.sh --push

deploy-nginx:
  tags:
    - linux
  stage: deploy
  script:
    . ./deploy.sh -s Vulkan

