stages:
  - test
  - build
  - deploy

test:
  image: python:3.6
  tags:
    - docker
  stage: test
  variables:
    TRAVIS: "true"
  before_script:
  - python -V  # Print out python version for debugging
  script:
    - python -c "import os; print(os.environ)"
    - pip install numpy
    - pip install -r requirements.txt
    - python setup.py develop
    - pip install pytest flake8  # you can also use tox
    - pytest --ignore-glob="*clemb*" --ignore-glob="*uks*" tests/
  allow_failure: true

build:
  tags:
    - linux
  stage: build
  script:
    - ./buildnrun.sh -b 
    - ./buildnrun.sh --push

deploy:
  tags:
    - linux
  stage: deploy
  script:
    . ./docker-deploy.sh

