stages:
  - build
  - deploy

build:
  tags:
    - linux
  stage: build
  script:
    - ./buildnrun.sh -b 
    - ./buildnrun.sh --push

deploy-nginx:
  tags:
    - linux
  stage: deploy
  script:
    . ./docker-deploy_nginx.sh

deploy-main:
  tags:
    - linux
  stage: deploy
  script:
    . ./docker-deploy.sh

