name: pumahu
channels:
    - conda-forge
dependencies:
    - python=3.6
    - bqplot
    - cartopy
    - scikit-learn
    - tqdm
    - numpy
    - scipy
    - matplotlib
    - plotly=4.14.3
    - kaleido
    - pandas
    - netcdf4
    - xarray
    - obspy
    - panel
    - param
    - pip
    - ipykernel
    - pytest
    - pip:
        - filterpy
        - cachier
        - git+ssh://git@github.com/yannikbehr/nsampling.git
