name: pumahu
channels:
    - pyviz
    - conda-forge
dependencies:
    - python=3.6
    - bqplot
    - numpy
    - scipy
    - matplotlib
    - pandas
    - netcdf4
    - xarray
    - holoviz
    - panel
    - param
    - bokeh
    - pip
    - ipykernel
    - pytest
    - pip:
        - filterpy
        - progressbar2
        - git+https://github.com/yannikbehr/nsampling.git
