name: pumahu
channels:
    - conda-forge
dependencies:
    - python=3.8
    - importlib-metadata==4.13
    - ipdb==0.13
    - seaborn==0.11
    - cartopy==0.20
    - pytest==6.2
    - sphinx==4.2
    - mtspec==0.3
    - scikit-learn==1.0
    - tqdm==4.62
    - numpy==1.21
    - scipy==1.5
    - matplotlib==3.4
    - plotly=4.14.3
    - python-kaleido==0.2
    - pandas==1.3
    - netcdf4==1.5
    - xarray==0.19
    - obspy==1.2
    - nbformat==5.1
    - ipykernel==6.4
    - pip
    - pip:
        - filterpy==1.4
        - cachier==1.5
        - schedule>=1.1*
        - git+ssh://git@github.com/yannikbehr/nsampling.git
        - importlib-metadata==4.13
        - fastapi==0.89
        - uvicorn[standard]==0.20
