name: pumahu
channels:
    - conda-forge
dependencies:
    - python=3.9
    - importlib-metadata==4.13
    - ipdb
    - seaborn
    - cartopy
    - pytest
    - sphinx
    - mtspec
    - scikit-learn
    - tqdm
    - numpy
    - scipy
    - matplotlib
    - plotly=4.14.3
    - python-kaleido
    - pandas
    - netcdf4
    - xarray
    - obspy
    - pytest
    - nbformat
    - ipykernel
    - pip
    - pip:
        - filterpy
        - cachier
        - schedule>=1.1*
        - git+ssh://git@github.com/yannikbehr/nsampling.git
        - importlib-metadata==4.13